uploads = []
generated = []

[[outputs]]
id = "9y-r6vOj2jfP2Ot595gHQ"
uri = "file://ai-botflow-crm-design.zip"
type = "unspecified"
title = "CLICK TO DOWNLOAD — Ai Botflow CRM Design"
description = "ZIP file: ai-botflow-crm-design.zip"
logical_id = "2fd902b1-ef6d-48e3-99f4-aa53dc610e7b"
content_hash = "sha256:123be9d01305b0cad7d3ff105ca34618e44e82d0a8d2ac371c431f019315c65c"
size = 233925
mtime_ms = 1787628679602
storage_uri = "gcs://replit-rams-assets-pike/rams/assets/repl:336837c0-c45c-4430-b17e-efb98ec17a08/2fd902b1-ef6d-48e3-99f4-aa53dc610e7b/698af27c-ca48-449a-bb37-451e6fbe4053"
storage_version_token = "1787628798651073"
content_type = "application/octet-stream"
