import { ArrowUpRight, Bell, CheckCircle2, ChevronDown, Clock3, MessageCircle, MoreHorizontal, Plus, Send, Tag, TrendingUp, Users } from "lucide-react";
import { Avatar, ChannelIcon, Sidebar, Topbar } from "./_shared/Sidebar";

const activity = [
  ["Priya Sharma","WhatsApp","Can you share the pricing deck?","Qualified","Rahul K.","2m ago","PS"],["Noah Williams","Instagram","Loved the demo — want to see teams plan","Contacted","Amara L.","18m ago","NW"],["Aarav Mehta","Facebook","Thanks, I will confirm tomorrow.","Proposal","Rahul K.","42m ago","AM"],["Sofia Laurent","WhatsApp","Booking a call for next week","New","Mia T.","1h ago","SL"],["Ethan Clarke","Instagram","The annual option works for us.","Won","Amara L.","2h ago","EC"],["Ishita Rao","WhatsApp","Please send the implementation timeline","Qualified","Rahul K.","3h ago","IR"],["Liam Chen","Facebook","Is there an integration with Stripe?","Contacted","Mia T.","4h ago","LC"],["Maya Patel","WhatsApp","We are ready to get started.","Won","Rahul K.","5h ago","MP"],
] as const;
const stages = [["New",340,"#3b82f6"],["Contacted",218,"#eab308"],["Qualified",156,"#8b5cf6"],["Proposal",89,"#f97316"],["Won",67,"#22c55e"],["Lost",34,"#ef4444"]];

export function Dashboard() {
  return <div className="min-h-[100dvh] bg-[#f5f8fb] flex text-slate-800"><Sidebar /><main className="min-w-0 flex-1"><Topbar title="Good morning, Rahul" subtitle="Here’s what’s happening across your customer conversations."/><div className="p-7 space-y-6 max-w-[1600px]">
    <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">
      {[["Total Leads","2,847","+12.5% this week",TrendingUp,"#e7f8ed","text-[#159447]"],["Messages Sent","48,291","+8.2% this week",MessageCircle,"#e2f4ff","text-[#2188c9]"],["Active Contacts","1,204","+5.1% this week",Users,"#f0eaff","text-[#7950cc]"],["Campaigns Running","7","3 scheduled",Bell,"#fff0dd","text-[#d8871a]"]].map(([name,num,delta,Icon,bg,color]) => <div className="bg-white rounded-xl border border-slate-200 panel-shadow p-5" key={name as string}><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{name as string}</span><span style={{background:bg as string}} className={`h-8 w-8 rounded-lg flex items-center justify-center ${color}`}><Icon size={16}/></span></div><div className="mt-4 flex items-end justify-between"><div><div className="font-display font-bold text-2xl text-slate-900">{num as string}</div><div className={`mt-1 text-[11px] font-semibold ${name === "Campaigns Running" ? "text-amber-600" : "text-[#159447]"}`}><ArrowUpRight size={12} className="inline"/> {delta as string}</div></div><div className="flex items-end gap-1 h-9">{[12,17,14,22,18,27,25,34].map((h,i)=><i key={i} style={{height:h}} className={`w-1 rounded-full ${name === "Campaigns Running" ? "bg-amber-200" : "bg-[#9de8b8]"}`}/>)}</div></div></div>)}
    </div>
    <div className="grid xl:grid-cols-[1.45fr_1fr] gap-5">
      <section className="bg-white border border-slate-200 rounded-xl panel-shadow overflow-hidden"><div className="p-5 flex justify-between items-center border-b border-slate-100"><div><h2 className="font-display font-bold">Lead Pipeline Overview</h2><p className="text-xs text-slate-500 mt-1">A live view of your lead movement</p></div><button className="text-xs flex items-center gap-2 border rounded-md px-2.5 py-1.5 text-slate-600">This week <ChevronDown size={13}/></button></div><div className="p-5"><div className="h-48 flex items-end gap-3 sm:gap-6 border-b border-slate-100 pb-0">{stages.map(([label,value,color])=><div className="flex-1 h-full flex flex-col justify-end items-center gap-2" key={label as string}><span className="text-[11px] font-bold text-slate-600">{value as number}</span><div style={{height:`${(value as number)/340*125}px`,background:color as string}} className="w-full max-w-[58px] rounded-t-md opacity-90 hover:opacity-100 transition-opacity"/><span className="text-[10px] text-slate-500 mb-3">{label as string}</span></div>)}</div></div></section>
      <section className="bg-white border border-slate-200 rounded-xl panel-shadow p-5"><div className="flex justify-between"><div><h2 className="font-display font-bold">Channel Breakdown</h2><p className="text-xs text-slate-500 mt-1">Conversations by source</p></div><MoreHorizontal size={18} className="text-slate-400"/></div><div className="flex items-center gap-7 mt-5"><div className="h-32 w-32 rounded-full flex items-center justify-center" style={{background:"conic-gradient(#22c55e 0 58%, #d94685 58% 85%, #4285db 85% 100%)"}}><div className="h-20 w-20 rounded-full bg-white flex flex-col items-center justify-center"><span className="font-display font-bold text-xl">2.8k</span><span className="text-[10px] text-slate-400">total</span></div></div><div className="space-y-3 text-xs flex-1">{[["WhatsApp","58%","#22c55e"],["Instagram","27%","#d94685"],["Facebook","15%","#4285db"]].map(([l,v,c])=><div className="flex items-center justify-between" key={l}><span><i style={{background:c}} className="inline-block h-2 w-2 rounded-full mr-2"/>{l}</span><b>{v}</b></div>)}</div></div></section>
    </div>
    <div className="grid xl:grid-cols-[1.45fr_1fr] gap-5"><section className="bg-white border border-slate-200 rounded-xl panel-shadow overflow-hidden"><div className="p-5 flex justify-between items-center"><h2 className="font-display font-bold">Recent Activity</h2><button className="text-xs text-[#159447] font-semibold">View all activity <ArrowUpRight size={13} className="inline"/></button></div><div className="overflow-auto"><table className="w-full text-left min-w-[760px]"><thead className="bg-slate-50 border-y border-slate-100 text-[10px] uppercase tracking-wider text-slate-400"><tr>{["Contact","Channel","Last Message","Stage","Assigned to","Last activity"].map(x=><th className="px-5 py-3 font-bold" key={x}>{x}</th>)}</tr></thead><tbody>{activity.map(([name,ch,msg,stage,assignee,time,initials])=><tr className="border-b border-slate-50 text-xs hover:bg-slate-50/80" key={name}><td className="px-5 py-3"><div className="flex items-center gap-2.5"><Avatar initials={initials}/><span className="font-semibold text-slate-700">{name}</span></div></td><td className="px-5"><ChannelIcon channel={ch}/></td><td className="px-5 max-w-[190px] truncate text-slate-500">{msg}</td><td className="px-5"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold">{stage}</span></td><td className="px-5 text-slate-500">{assignee}</td><td className="px-5 text-slate-400">{time}</td></tr>)}</tbody></table></div></section>
      <div className="space-y-5"><section className="bg-white border border-slate-200 rounded-xl panel-shadow p-5"><div className="flex justify-between"><h2 className="font-display font-bold">Upcoming Follow-ups</h2><Clock3 size={17} className="text-slate-400"/></div><div className="mt-3 divide-y divide-slate-100">{[["Priya Sharma","WhatsApp","Today, 2:30 PM","Qualified"],["Noah Williams","Instagram","Today, 4:00 PM","Open"],["Aarav Mehta","Facebook","Tomorrow, 10:15 AM","Pending"],["Sofia Laurent","WhatsApp","Tomorrow, 1:00 PM","Open"],["Ishita Rao","WhatsApp","Fri, 11:45 AM","Pending"]].map(([n,c,t,s])=><div className="py-3 flex items-center gap-2.5" key={n}><ChannelIcon channel={c as "WhatsApp"}/><div className="flex-1"><div className="text-xs font-semibold">{n}</div><div className="text-[10px] text-slate-400 mt-0.5">{t}</div></div><span className="text-[10px] rounded-full bg-amber-50 text-amber-700 px-2 py-1">{s}</span></div>)}</div></section><section className="bg-white border border-slate-200 rounded-xl panel-shadow p-5"><h2 className="font-display font-bold">Campaign Performance</h2><div className="mt-3 space-y-3">{[["Summer onboarding","24.6k","94.2%","12.8%"],["Product launch — May","16.3k","91.8%","9.4%"],["VIP reactivation","7.4k","96.1%","18.6%"]].map(x=><div className="grid grid-cols-[1fr_48px_55px_48px] gap-2 text-[10px] border-t border-slate-100 pt-3" key={x[0]}><span className="font-semibold">{x[0]}</span><span className="text-slate-500">{x[1]} sent</span><span className="text-[#159447]">{x[2]} delivered</span><span className="text-blue-600">{x[3]} replied</span></div>)}</div></section></div></div>
    <div className="grid lg:grid-cols-[1.45fr_1fr] gap-5"><section className="rounded-xl border border-[#b8eac9] bg-[#effbf3] p-5"><div className="flex items-center gap-2 text-[#13783d] font-bold text-sm"><SparkleIcon/><span>AI Reply Suggestions Active</span><span className="ml-auto rounded-full bg-white/70 px-2 py-1 text-[10px] font-semibold">Live</span></div><div className="mt-3 grid md:grid-cols-3 gap-3">{["Pricing question → highlight the annual saving","Demo request → offer Tuesday 11:00 AM","Integration query → share the Stripe guide"].map((x,i)=><div className="bg-white/75 rounded-lg p-3 text-xs text-slate-600 border border-[#d5f3df]" key={x}><div className="text-[10px] text-[#159447] font-bold mb-1">Suggestion 0{i+1}</div>{x}</div>)}</div></section><section className="bg-white border border-slate-200 rounded-xl panel-shadow p-5"><h2 className="font-display font-bold text-sm">Top Tags</h2><div className="flex flex-wrap gap-2 mt-3">{["Hot lead","VIP","Enterprise","Demo booked","Q2 launch","Renewal","High intent"].map((x,i)=><span className={`rounded-md px-2.5 py-1.5 text-[10px] font-semibold ${i%3===0?"bg-[#e5f7eb] text-[#14803e]":i%3===1?"bg-[#e8f1ff] text-[#336ec3]":"bg-[#fff1df] text-[#b16c14]"}`} key={x}><Tag size={11} className="inline mr-1"/>{x}</span>)}</div></section></div>
  </div></main></div>;
}
function SparkleIcon(){return <span className="h-6 w-6 rounded-md bg-[#c9f1d6] flex items-center justify-center"><TrendingUp size={14}/></span>}