// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm-saas/AISequence.tsx": () => import("../components/mockups/crm-saas/AISequence.tsx"),
  "./components/mockups/crm-saas/ChatbotFlow.tsx": () => import("../components/mockups/crm-saas/ChatbotFlow.tsx"),
  "./components/mockups/crm-saas/Dashboard.tsx": () => import("../components/mockups/crm-saas/Dashboard.tsx"),
  "./components/mockups/crm-saas/LeadsPipeline.tsx": () => import("../components/mockups/crm-saas/LeadsPipeline.tsx"),
  "./components/mockups/crm-saas/UnifiedInbox.tsx": () => import("../components/mockups/crm-saas/UnifiedInbox.tsx")
};
